sudo: required
services:
  - docker

before_install:
  - docker build -t prasunmax/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prasunmax/react-test npm run test -- --coverage

after_success:
  - docker build -t prasunmax/multi-client ./client
  - docker build -t prasunmax/multi-nginx  ./nginx
  - docker build -t prasunmax/multi-server ./server
  - docker build -t prasunmax/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push prasunmax/multi-client
  - docker push prasunmax/multi-nginx
  - docker push prasunmax/multi-server
  - docker push prasunmax/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-401275114950"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access:key: $AWS_SECRET_KEY